<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head><title>Select Movie Record</title></head>
<body>
    <h1>Movie Database Lookup</h1>
    <p>Please select a movie ID to view its details:</p>
    
    <jsp:useBean id='myDB' class='database.DbBean' />
    
    <%-- Output the dropdown form generated by the bean --%>
    <%= myDB.getDropdownMenu() %>
    
    <br /><a href="index.jsp">Back to Index</a>
</body>
</html>